### ISSUE TITLE
Two quick suggestions

### ISSUE THREAD

**Issue by blackary** [antoineeripret/streamlit-archive#2]
You could add a nice custom url, like `streamlit-archive.streamlit.app` (https://docs.streamlit.io/knowledge-base/deploy/custom-subdomains)
You could also switch from a start and end date picker to a single date range picker, if you want

**Comment by antoineeripret** [comment]
Hi @blackary, 

Thank you for your comment. 

> You could add a nice custom url, like streamlit-archive.streamlit.app (https://docs.streamlit.io/knowledge-base/deploy/custom-subdomains)

Agreed but too late. I don't want current users to get a 404 error :) 

> You could also switch from a start and end date picker to a single date range picker, if you want

I'd rather stick with https://docs.streamlit.io/library/api-reference/widgets/st.date_input to avoid updating the code. The current behavior is clear. 

If you have other feedbacks, do not hesitate to let me know and open another discussion. 

Thanks!

**Comment by blackary** [comment]
Makes sense. On the second suggestion, just so you know, you don't need to use a different widget at all. if you provide a tuple of dates for the starting value, st.date_input has you pick a date range, rather than a single date.

**Comment by antoineeripret** [comment]
Ah, didn't know that. I'll update it the next time I want to add something to the app. Thanks, @blackary !
